package com.easybasic.basic.model;

import java.io.Serializable;
import java.util.Date;

public class IntranetIp implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_intranetip.pkid
     *
     * @mbggenerated
     */
    private Integer pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_intranetip.ipstart
     *
     * @mbggenerated
     */
    private Long ipstart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_intranetip.ipend
     *
     * @mbggenerated
     */
    private Long ipend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_intranetip.ipstartstr
     *
     * @mbggenerated
     */
    private String ipstartstr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_intranetip.ipendstr
     *
     * @mbggenerated
     */
    private String ipendstr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_intranetip.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_intranetip.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table basic_intranetip
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_intranetip.pkid
     *
     * @return the value of basic_intranetip.pkid
     *
     * @mbggenerated
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_intranetip.pkid
     *
     * @param pkid the value for basic_intranetip.pkid
     *
     * @mbggenerated
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_intranetip.ipstart
     *
     * @return the value of basic_intranetip.ipstart
     *
     * @mbggenerated
     */
    public Long getIpstart() {
        return ipstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_intranetip.ipstart
     *
     * @param ipstart the value for basic_intranetip.ipstart
     *
     * @mbggenerated
     */
    public void setIpstart(Long ipstart) {
        this.ipstart = ipstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_intranetip.ipend
     *
     * @return the value of basic_intranetip.ipend
     *
     * @mbggenerated
     */
    public Long getIpend() {
        return ipend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_intranetip.ipend
     *
     * @param ipend the value for basic_intranetip.ipend
     *
     * @mbggenerated
     */
    public void setIpend(Long ipend) {
        this.ipend = ipend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_intranetip.ipstartstr
     *
     * @return the value of basic_intranetip.ipstartstr
     *
     * @mbggenerated
     */
    public String getIpstartstr() {
        return ipstartstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_intranetip.ipstartstr
     *
     * @param ipstartstr the value for basic_intranetip.ipstartstr
     *
     * @mbggenerated
     */
    public void setIpstartstr(String ipstartstr) {
        this.ipstartstr = ipstartstr == null ? null : ipstartstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_intranetip.ipendstr
     *
     * @return the value of basic_intranetip.ipendstr
     *
     * @mbggenerated
     */
    public String getIpendstr() {
        return ipendstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_intranetip.ipendstr
     *
     * @param ipendstr the value for basic_intranetip.ipendstr
     *
     * @mbggenerated
     */
    public void setIpendstr(String ipendstr) {
        this.ipendstr = ipendstr == null ? null : ipendstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_intranetip.createtime
     *
     * @return the value of basic_intranetip.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_intranetip.createtime
     *
     * @param createtime the value for basic_intranetip.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_intranetip.remark
     *
     * @return the value of basic_intranetip.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_intranetip.remark
     *
     * @param remark the value for basic_intranetip.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_intranetip
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IntranetIp other = (IntranetIp) that;
        return (this.getPkid() == null ? other.getPkid() == null : this.getPkid().equals(other.getPkid()))
            && (this.getIpstart() == null ? other.getIpstart() == null : this.getIpstart().equals(other.getIpstart()))
            && (this.getIpend() == null ? other.getIpend() == null : this.getIpend().equals(other.getIpend()))
            && (this.getIpstartstr() == null ? other.getIpstartstr() == null : this.getIpstartstr().equals(other.getIpstartstr()))
            && (this.getIpendstr() == null ? other.getIpendstr() == null : this.getIpendstr().equals(other.getIpendstr()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_intranetip
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPkid() == null) ? 0 : getPkid().hashCode());
        result = prime * result + ((getIpstart() == null) ? 0 : getIpstart().hashCode());
        result = prime * result + ((getIpend() == null) ? 0 : getIpend().hashCode());
        result = prime * result + ((getIpstartstr() == null) ? 0 : getIpstartstr().hashCode());
        result = prime * result + ((getIpendstr() == null) ? 0 : getIpendstr().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_intranetip
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pkid=").append(pkid);
        sb.append(", ipstart=").append(ipstart);
        sb.append(", ipend=").append(ipend);
        sb.append(", ipstartstr=").append(ipstartstr);
        sb.append(", ipendstr=").append(ipendstr);
        sb.append(", createtime=").append(createtime);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}