package com.easybasic.basic.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class OpLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_oplog.pkid
     *
     * @mbggenerated
     */
    private Integer pkid;

    /**
     * 0为内部应用；1为第三方应用
     */
    private int type;
    private String code;

    private String opapp;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_oplog.opmodule
     *
     * @mbggenerated
     */
    private String opmodule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_oplog.opip
     *
     * @mbggenerated
     */
    private String opip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_oplog.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_oplog.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_oplog.createtime
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_oplog.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_oplog.opremark
     *
     * @mbggenerated
     */
    private String opremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table basic_oplog
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public String getOpapp() {
        return opapp;
    }

    public void setOpapp(String opapp) {
        this.opapp = opapp;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_oplog.pkid
     *
     * @return the value of basic_oplog.pkid
     *
     * @mbggenerated
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_oplog.pkid
     *
     * @param pkid the value for basic_oplog.pkid
     *
     * @mbggenerated
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_oplog.opmodule
     *
     * @return the value of basic_oplog.opmodule
     *
     * @mbggenerated
     */
    public String getOpmodule() {
        return opmodule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_oplog.opmodule
     *
     * @param opmodule the value for basic_oplog.opmodule
     *
     * @mbggenerated
     */
    public void setOpmodule(String opmodule) {
        this.opmodule = opmodule == null ? null : opmodule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_oplog.opip
     *
     * @return the value of basic_oplog.opip
     *
     * @mbggenerated
     */
    public String getOpip() {
        return opip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_oplog.opip
     *
     * @param opip the value for basic_oplog.opip
     *
     * @mbggenerated
     */
    public void setOpip(String opip) {
        this.opip = opip == null ? null : opip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_oplog.userid
     *
     * @return the value of basic_oplog.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_oplog.userid
     *
     * @param userid the value for basic_oplog.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_oplog.username
     *
     * @return the value of basic_oplog.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_oplog.username
     *
     * @param username the value for basic_oplog.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_oplog.createtime
     *
     * @return the value of basic_oplog.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_oplog.createtime
     *
     * @param createtime the value for basic_oplog.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_oplog.status
     *
     * @return the value of basic_oplog.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_oplog.status
     *
     * @param status the value for basic_oplog.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_oplog.opremark
     *
     * @return the value of basic_oplog.opremark
     *
     * @mbggenerated
     */
    public String getOpremark() {
        return opremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_oplog.opremark
     *
     * @param opremark the value for basic_oplog.opremark
     *
     * @mbggenerated
     */
    public void setOpremark(String opremark) {
        this.opremark = opremark == null ? null : opremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_oplog
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OpLog other = (OpLog) that;
        return (this.getPkid() == null ? other.getPkid() == null : this.getPkid().equals(other.getPkid()))
            && (this.getOpmodule() == null ? other.getOpmodule() == null : this.getOpmodule().equals(other.getOpmodule()))
            && (this.getOpip() == null ? other.getOpip() == null : this.getOpip().equals(other.getOpip()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getOpremark() == null ? other.getOpremark() == null : this.getOpremark().equals(other.getOpremark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_oplog
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPkid() == null) ? 0 : getPkid().hashCode());
        result = prime * result + ((getOpmodule() == null) ? 0 : getOpmodule().hashCode());
        result = prime * result + ((getOpip() == null) ? 0 : getOpip().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getOpremark() == null) ? 0 : getOpremark().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_oplog
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pkid=").append(pkid);
        sb.append(", opmodule=").append(opmodule);
        sb.append(", opip=").append(opip);
        sb.append(", userid=").append(userid);
        sb.append(", username=").append(username);
        sb.append(", createtime=").append(createtime);
        sb.append(", status=").append(status);
        sb.append(", opremark=").append(opremark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}