package com.easybasic.basic.model;

import java.io.Serializable;
import java.util.Date;

public class PurviewUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_purviewuser.pkid
     *
     * @mbggenerated
     */
    private Integer pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_purviewuser.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_purviewuser.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_purviewuser.modulepurviews
     *
     * @mbggenerated
     */
    private String modulepurviews;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_purviewuser.menupurviews
     *
     * @mbggenerated
     */
    private String menupurviews;

    private String itempurviews;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table basic_purviewuser
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public String getItempurviews() {
        return itempurviews;
    }

    public void setItempurviews(String itempurviews) {
        this.itempurviews = itempurviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_purviewuser.pkid
     *
     * @return the value of basic_purviewuser.pkid
     *
     * @mbggenerated
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_purviewuser.pkid
     *
     * @param pkid the value for basic_purviewuser.pkid
     *
     * @mbggenerated
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_purviewuser.userid
     *
     * @return the value of basic_purviewuser.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_purviewuser.userid
     *
     * @param userid the value for basic_purviewuser.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_purviewuser.createtime
     *
     * @return the value of basic_purviewuser.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_purviewuser.createtime
     *
     * @param createtime the value for basic_purviewuser.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_purviewuser.modulepurviews
     *
     * @return the value of basic_purviewuser.modulepurviews
     *
     * @mbggenerated
     */
    public String getModulepurviews() {
        return modulepurviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_purviewuser.modulepurviews
     *
     * @param modulepurviews the value for basic_purviewuser.modulepurviews
     *
     * @mbggenerated
     */
    public void setModulepurviews(String modulepurviews) {
        this.modulepurviews = modulepurviews == null ? null : modulepurviews.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_purviewuser.menupurviews
     *
     * @return the value of basic_purviewuser.menupurviews
     *
     * @mbggenerated
     */
    public String getMenupurviews() {
        return menupurviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_purviewuser.menupurviews
     *
     * @param menupurviews the value for basic_purviewuser.menupurviews
     *
     * @mbggenerated
     */
    public void setMenupurviews(String menupurviews) {
        this.menupurviews = menupurviews == null ? null : menupurviews.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_purviewuser
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PurviewUser other = (PurviewUser) that;
        return (this.getPkid() == null ? other.getPkid() == null : this.getPkid().equals(other.getPkid()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getModulepurviews() == null ? other.getModulepurviews() == null : this.getModulepurviews().equals(other.getModulepurviews()))
            && (this.getMenupurviews() == null ? other.getMenupurviews() == null : this.getMenupurviews().equals(other.getMenupurviews()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_purviewuser
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPkid() == null) ? 0 : getPkid().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getModulepurviews() == null) ? 0 : getModulepurviews().hashCode());
        result = prime * result + ((getMenupurviews() == null) ? 0 : getMenupurviews().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_purviewuser
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pkid=").append(pkid);
        sb.append(", userid=").append(userid);
        sb.append(", createtime=").append(createtime);
        sb.append(", modulepurviews=").append(modulepurviews);
        sb.append(", menupurviews=").append(menupurviews);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    private User user;
    private String roleStrs;

    public String getRoleStrs() {
        return roleStrs;
    }

    public void setRoleStrs(String roleStrs) {
        this.roleStrs = roleStrs;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

}