package com.easybasic.basic.model;

import java.io.Serializable;
import java.util.Date;

public class PurviewRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_purviewrole.pkid
     *
     * @mbggenerated
     */
    private Integer pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_purviewrole.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_purviewrole.sortnum
     *
     * @mbggenerated
     */
    private Integer sortnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_purviewrole.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_purviewrole.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_purviewrole.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_purviewrole.modulepurviews
     *
     * @mbggenerated
     */
    private String modulepurviews;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_purviewrole.menupurviews
     *
     * @mbggenerated
     */
    private String menupurviews;

    private String itempurviews;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table basic_purviewrole
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_purviewrole.pkid
     *
     * @return the value of basic_purviewrole.pkid
     *
     * @mbggenerated
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_purviewrole.pkid
     *
     * @param pkid the value for basic_purviewrole.pkid
     *
     * @mbggenerated
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_purviewrole.name
     *
     * @return the value of basic_purviewrole.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_purviewrole.name
     *
     * @param name the value for basic_purviewrole.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_purviewrole.sortnum
     *
     * @return the value of basic_purviewrole.sortnum
     *
     * @mbggenerated
     */
    public Integer getSortnum() {
        return sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_purviewrole.sortnum
     *
     * @param sortnum the value for basic_purviewrole.sortnum
     *
     * @mbggenerated
     */
    public void setSortnum(Integer sortnum) {
        this.sortnum = sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_purviewrole.status
     *
     * @return the value of basic_purviewrole.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_purviewrole.status
     *
     * @param status the value for basic_purviewrole.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_purviewrole.createtime
     *
     * @return the value of basic_purviewrole.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_purviewrole.createtime
     *
     * @param createtime the value for basic_purviewrole.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_purviewrole.remark
     *
     * @return the value of basic_purviewrole.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_purviewrole.remark
     *
     * @param remark the value for basic_purviewrole.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_purviewrole.modulepurviews
     *
     * @return the value of basic_purviewrole.modulepurviews
     *
     * @mbggenerated
     */
    public String getModulepurviews() {
        return modulepurviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_purviewrole.modulepurviews
     *
     * @param modulepurviews the value for basic_purviewrole.modulepurviews
     *
     * @mbggenerated
     */
    public void setModulepurviews(String modulepurviews) {
        this.modulepurviews = modulepurviews == null ? null : modulepurviews.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_purviewrole.menupurviews
     *
     * @return the value of basic_purviewrole.menupurviews
     *
     * @mbggenerated
     */
    public String getMenupurviews() {
        return menupurviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_purviewrole.menupurviews
     *
     * @param menupurviews the value for basic_purviewrole.menupurviews
     *
     * @mbggenerated
     */
    public void setMenupurviews(String menupurviews) {
        this.menupurviews = menupurviews == null ? null : menupurviews.trim();
    }

    public String getItempurviews() {
        return itempurviews;
    }

    public void setItempurviews(String itempurviews) {
        this.itempurviews = itempurviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_purviewrole
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PurviewRole other = (PurviewRole) that;
        return (this.getPkid() == null ? other.getPkid() == null : this.getPkid().equals(other.getPkid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getSortnum() == null ? other.getSortnum() == null : this.getSortnum().equals(other.getSortnum()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getModulepurviews() == null ? other.getModulepurviews() == null : this.getModulepurviews().equals(other.getModulepurviews()))
            && (this.getMenupurviews() == null ? other.getMenupurviews() == null : this.getMenupurviews().equals(other.getMenupurviews()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_purviewrole
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPkid() == null) ? 0 : getPkid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getSortnum() == null) ? 0 : getSortnum().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getModulepurviews() == null) ? 0 : getModulepurviews().hashCode());
        result = prime * result + ((getMenupurviews() == null) ? 0 : getMenupurviews().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_purviewrole
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pkid=").append(pkid);
        sb.append(", name=").append(name);
        sb.append(", sortnum=").append(sortnum);
        sb.append(", status=").append(status);
        sb.append(", createtime=").append(createtime);
        sb.append(", remark=").append(remark);
        sb.append(", modulepurviews=").append(modulepurviews);
        sb.append(", menupurviews=").append(menupurviews);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}