package com.easybasic.basic.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class SchoolYearTerm implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_schoolyearterm.pkid
     *
     * @mbggenerated
     */
    private Integer pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_schoolyearterm.schoolid
     *
     * @mbggenerated
     */
    private Integer schoolid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_schoolyearterm.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_schoolyearterm.schoolterm
     *
     * @mbggenerated
     */
    private Integer schoolterm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_schoolyearterm.weekdays
     *
     * @mbggenerated
     */
    private Integer weekdays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_schoolyearterm.courselen
     *
     * @mbggenerated
     */
    private Integer courselen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_schoolyearterm.morningsessions
     *
     * @mbggenerated
     */
    private Integer morningsessions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_schoolyearterm.afternoonsessions
     *
     * @mbggenerated
     */
    private Integer afternoonsessions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_schoolyearterm.eveningsessions
     *
     * @mbggenerated
     */
    private Integer eveningsessions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_schoolyearterm.workstartdate
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date workstartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_schoolyearterm.workenddate
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date workenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_schoolyearterm.learnstartdate
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date learnstartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_schoolyearterm.learnenddate
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date learnenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_schoolyearterm.createtime
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table basic_schoolyearterm
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_schoolyearterm.pkid
     *
     * @return the value of basic_schoolyearterm.pkid
     *
     * @mbggenerated
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_schoolyearterm.pkid
     *
     * @param pkid the value for basic_schoolyearterm.pkid
     *
     * @mbggenerated
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_schoolyearterm.schoolid
     *
     * @return the value of basic_schoolyearterm.schoolid
     *
     * @mbggenerated
     */
    public Integer getSchoolid() {
        return schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_schoolyearterm.schoolid
     *
     * @param schoolid the value for basic_schoolyearterm.schoolid
     *
     * @mbggenerated
     */
    public void setSchoolid(Integer schoolid) {
        this.schoolid = schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_schoolyearterm.name
     *
     * @return the value of basic_schoolyearterm.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_schoolyearterm.name
     *
     * @param name the value for basic_schoolyearterm.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_schoolyearterm.schoolterm
     *
     * @return the value of basic_schoolyearterm.schoolterm
     *
     * @mbggenerated
     */
    public Integer getSchoolterm() {
        return schoolterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_schoolyearterm.schoolterm
     *
     * @param schoolterm the value for basic_schoolyearterm.schoolterm
     *
     * @mbggenerated
     */
    public void setSchoolterm(Integer schoolterm) {
        this.schoolterm = schoolterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_schoolyearterm.weekdays
     *
     * @return the value of basic_schoolyearterm.weekdays
     *
     * @mbggenerated
     */
    public Integer getWeekdays() {
        return weekdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_schoolyearterm.weekdays
     *
     * @param weekdays the value for basic_schoolyearterm.weekdays
     *
     * @mbggenerated
     */
    public void setWeekdays(Integer weekdays) {
        this.weekdays = weekdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_schoolyearterm.courselen
     *
     * @return the value of basic_schoolyearterm.courselen
     *
     * @mbggenerated
     */
    public Integer getCourselen() {
        return courselen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_schoolyearterm.courselen
     *
     * @param courselen the value for basic_schoolyearterm.courselen
     *
     * @mbggenerated
     */
    public void setCourselen(Integer courselen) {
        this.courselen = courselen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_schoolyearterm.morningsessions
     *
     * @return the value of basic_schoolyearterm.morningsessions
     *
     * @mbggenerated
     */
    public Integer getMorningsessions() {
        return morningsessions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_schoolyearterm.morningsessions
     *
     * @param morningsessions the value for basic_schoolyearterm.morningsessions
     *
     * @mbggenerated
     */
    public void setMorningsessions(Integer morningsessions) {
        this.morningsessions = morningsessions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_schoolyearterm.afternoonsessions
     *
     * @return the value of basic_schoolyearterm.afternoonsessions
     *
     * @mbggenerated
     */
    public Integer getAfternoonsessions() {
        return afternoonsessions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_schoolyearterm.afternoonsessions
     *
     * @param afternoonsessions the value for basic_schoolyearterm.afternoonsessions
     *
     * @mbggenerated
     */
    public void setAfternoonsessions(Integer afternoonsessions) {
        this.afternoonsessions = afternoonsessions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_schoolyearterm.eveningsessions
     *
     * @return the value of basic_schoolyearterm.eveningsessions
     *
     * @mbggenerated
     */
    public Integer getEveningsessions() {
        return eveningsessions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_schoolyearterm.eveningsessions
     *
     * @param eveningsessions the value for basic_schoolyearterm.eveningsessions
     *
     * @mbggenerated
     */
    public void setEveningsessions(Integer eveningsessions) {
        this.eveningsessions = eveningsessions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_schoolyearterm.workstartdate
     *
     * @return the value of basic_schoolyearterm.workstartdate
     *
     * @mbggenerated
     */
    public Date getWorkstartdate() {
        return workstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_schoolyearterm.workstartdate
     *
     * @param workstartdate the value for basic_schoolyearterm.workstartdate
     *
     * @mbggenerated
     */
    public void setWorkstartdate(Date workstartdate) {
        this.workstartdate = workstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_schoolyearterm.workenddate
     *
     * @return the value of basic_schoolyearterm.workenddate
     *
     * @mbggenerated
     */
    public Date getWorkenddate() {
        return workenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_schoolyearterm.workenddate
     *
     * @param workenddate the value for basic_schoolyearterm.workenddate
     *
     * @mbggenerated
     */
    public void setWorkenddate(Date workenddate) {
        this.workenddate = workenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_schoolyearterm.learnstartdate
     *
     * @return the value of basic_schoolyearterm.learnstartdate
     *
     * @mbggenerated
     */
    public Date getLearnstartdate() {
        return learnstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_schoolyearterm.learnstartdate
     *
     * @param learnstartdate the value for basic_schoolyearterm.learnstartdate
     *
     * @mbggenerated
     */
    public void setLearnstartdate(Date learnstartdate) {
        this.learnstartdate = learnstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_schoolyearterm.learnenddate
     *
     * @return the value of basic_schoolyearterm.learnenddate
     *
     * @mbggenerated
     */
    public Date getLearnenddate() {
        return learnenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_schoolyearterm.learnenddate
     *
     * @param learnenddate the value for basic_schoolyearterm.learnenddate
     *
     * @mbggenerated
     */
    public void setLearnenddate(Date learnenddate) {
        this.learnenddate = learnenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_schoolyearterm.createtime
     *
     * @return the value of basic_schoolyearterm.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_schoolyearterm.createtime
     *
     * @param createtime the value for basic_schoolyearterm.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_schoolyearterm
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SchoolYearTerm other = (SchoolYearTerm) that;
        return (this.getPkid() == null ? other.getPkid() == null : this.getPkid().equals(other.getPkid()))
            && (this.getSchoolid() == null ? other.getSchoolid() == null : this.getSchoolid().equals(other.getSchoolid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getSchoolterm() == null ? other.getSchoolterm() == null : this.getSchoolterm().equals(other.getSchoolterm()))
            && (this.getWeekdays() == null ? other.getWeekdays() == null : this.getWeekdays().equals(other.getWeekdays()))
            && (this.getCourselen() == null ? other.getCourselen() == null : this.getCourselen().equals(other.getCourselen()))
            && (this.getMorningsessions() == null ? other.getMorningsessions() == null : this.getMorningsessions().equals(other.getMorningsessions()))
            && (this.getAfternoonsessions() == null ? other.getAfternoonsessions() == null : this.getAfternoonsessions().equals(other.getAfternoonsessions()))
            && (this.getEveningsessions() == null ? other.getEveningsessions() == null : this.getEveningsessions().equals(other.getEveningsessions()))
            && (this.getWorkstartdate() == null ? other.getWorkstartdate() == null : this.getWorkstartdate().equals(other.getWorkstartdate()))
            && (this.getWorkenddate() == null ? other.getWorkenddate() == null : this.getWorkenddate().equals(other.getWorkenddate()))
            && (this.getLearnstartdate() == null ? other.getLearnstartdate() == null : this.getLearnstartdate().equals(other.getLearnstartdate()))
            && (this.getLearnenddate() == null ? other.getLearnenddate() == null : this.getLearnenddate().equals(other.getLearnenddate()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_schoolyearterm
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPkid() == null) ? 0 : getPkid().hashCode());
        result = prime * result + ((getSchoolid() == null) ? 0 : getSchoolid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getSchoolterm() == null) ? 0 : getSchoolterm().hashCode());
        result = prime * result + ((getWeekdays() == null) ? 0 : getWeekdays().hashCode());
        result = prime * result + ((getCourselen() == null) ? 0 : getCourselen().hashCode());
        result = prime * result + ((getMorningsessions() == null) ? 0 : getMorningsessions().hashCode());
        result = prime * result + ((getAfternoonsessions() == null) ? 0 : getAfternoonsessions().hashCode());
        result = prime * result + ((getEveningsessions() == null) ? 0 : getEveningsessions().hashCode());
        result = prime * result + ((getWorkstartdate() == null) ? 0 : getWorkstartdate().hashCode());
        result = prime * result + ((getWorkenddate() == null) ? 0 : getWorkenddate().hashCode());
        result = prime * result + ((getLearnstartdate() == null) ? 0 : getLearnstartdate().hashCode());
        result = prime * result + ((getLearnenddate() == null) ? 0 : getLearnenddate().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_schoolyearterm
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pkid=").append(pkid);
        sb.append(", schoolid=").append(schoolid);
        sb.append(", name=").append(name);
        sb.append(", schoolterm=").append(schoolterm);
        sb.append(", weekdays=").append(weekdays);
        sb.append(", courselen=").append(courselen);
        sb.append(", morningsessions=").append(morningsessions);
        sb.append(", afternoonsessions=").append(afternoonsessions);
        sb.append(", eveningsessions=").append(eveningsessions);
        sb.append(", workstartdate=").append(workstartdate);
        sb.append(", workenddate=").append(workenddate);
        sb.append(", learnstartdate=").append(learnstartdate);
        sb.append(", learnenddate=").append(learnenddate);
        sb.append(", createtime=").append(createtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    private String schoolTermName;

    public String getSchoolTermName() {
        return schoolTermName;
    }

    public void setSchoolTermName(String schoolTermName) {
        this.schoolTermName = schoolTermName;
    }
}