package com.easybasic.basic.model;

import java.io.Serializable;

public class SiteConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_siteconfig.pkid
     *
     * @mbggenerated
     */
    private Integer pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_siteconfig.isonlyallowintranetip
     *
     * @mbggenerated
     */
    private Integer isonlyallowintranetip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table basic_siteconfig
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_siteconfig.pkid
     *
     * @return the value of basic_siteconfig.pkid
     *
     * @mbggenerated
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_siteconfig.pkid
     *
     * @param pkid the value for basic_siteconfig.pkid
     *
     * @mbggenerated
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_siteconfig.isonlyallowintranetip
     *
     * @return the value of basic_siteconfig.isonlyallowintranetip
     *
     * @mbggenerated
     */
    public Integer getIsonlyallowintranetip() {
        return isonlyallowintranetip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_siteconfig.isonlyallowintranetip
     *
     * @param isonlyallowintranetip the value for basic_siteconfig.isonlyallowintranetip
     *
     * @mbggenerated
     */
    public void setIsonlyallowintranetip(Integer isonlyallowintranetip) {
        this.isonlyallowintranetip = isonlyallowintranetip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_siteconfig
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SiteConfig other = (SiteConfig) that;
        return (this.getPkid() == null ? other.getPkid() == null : this.getPkid().equals(other.getPkid()))
            && (this.getIsonlyallowintranetip() == null ? other.getIsonlyallowintranetip() == null : this.getIsonlyallowintranetip().equals(other.getIsonlyallowintranetip()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_siteconfig
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPkid() == null) ? 0 : getPkid().hashCode());
        result = prime * result + ((getIsonlyallowintranetip() == null) ? 0 : getIsonlyallowintranetip().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_siteconfig
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pkid=").append(pkid);
        sb.append(", isonlyallowintranetip=").append(isonlyallowintranetip);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}