package com.easybasic.basic.model;

import java.io.Serializable;

public class Student implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_student.pkid
     *
     * @mbggenerated
     */
    private Integer pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_student.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_student.stuid
     *
     * @mbggenerated
     */
    private String stuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_student.stunum
     *
     * @mbggenerated
     */
    private String stunum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table basic_student
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_student.pkid
     *
     * @return the value of basic_student.pkid
     *
     * @mbggenerated
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_student.pkid
     *
     * @param pkid the value for basic_student.pkid
     *
     * @mbggenerated
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_student.userid
     *
     * @return the value of basic_student.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_student.userid
     *
     * @param userid the value for basic_student.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_student.stuid
     *
     * @return the value of basic_student.stuid
     *
     * @mbggenerated
     */
    public String getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_student.stuid
     *
     * @param stuid the value for basic_student.stuid
     *
     * @mbggenerated
     */
    public void setStuid(String stuid) {
        this.stuid = stuid == null ? null : stuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_student.stunum
     *
     * @return the value of basic_student.stunum
     *
     * @mbggenerated
     */
    public String getStunum() {
        return stunum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_student.stunum
     *
     * @param stunum the value for basic_student.stunum
     *
     * @mbggenerated
     */
    public void setStunum(String stunum) {
        this.stunum = stunum == null ? null : stunum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_student
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Student other = (Student) that;
        return (this.getPkid() == null ? other.getPkid() == null : this.getPkid().equals(other.getPkid()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getStuid() == null ? other.getStuid() == null : this.getStuid().equals(other.getStuid()))
            && (this.getStunum() == null ? other.getStunum() == null : this.getStunum().equals(other.getStunum()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_student
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPkid() == null) ? 0 : getPkid().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getStuid() == null) ? 0 : getStuid().hashCode());
        result = prime * result + ((getStunum() == null) ? 0 : getStunum().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_student
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pkid=").append(pkid);
        sb.append(", userid=").append(userid);
        sb.append(", stuid=").append(stuid);
        sb.append(", stunum=").append(stunum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}