package com.easybasic.basic.model;

import java.io.Serializable;
import java.util.Date;

public class Unit implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_unit.pkid
     *
     * @mbggenerated
     */
    private Integer pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_unit.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_unit.parentid
     *
     * @mbggenerated
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_unit.sortnum
     *
     * @mbggenerated
     */
    private Integer sortnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_unit.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_unit.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_unit.stageids
     *
     * @mbggenerated
     */
    private String stageids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_unit.fpinyin
     *
     * @mbggenerated
     */
    private String fpinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_unit.spinyin
     *
     * @mbggenerated
     */
    private String spinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_unit.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    private int manageuser;

    public int getManageuser() {
        return manageuser;
    }

    public void setManageuser(int manageuser) {
        this.manageuser = manageuser;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table basic_unit
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_unit.pkid
     *
     * @return the value of basic_unit.pkid
     *
     * @mbggenerated
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_unit.pkid
     *
     * @param pkid the value for basic_unit.pkid
     *
     * @mbggenerated
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_unit.name
     *
     * @return the value of basic_unit.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_unit.name
     *
     * @param name the value for basic_unit.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_unit.parentid
     *
     * @return the value of basic_unit.parentid
     *
     * @mbggenerated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_unit.parentid
     *
     * @param parentid the value for basic_unit.parentid
     *
     * @mbggenerated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_unit.sortnum
     *
     * @return the value of basic_unit.sortnum
     *
     * @mbggenerated
     */
    public Integer getSortnum() {
        return sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_unit.sortnum
     *
     * @param sortnum the value for basic_unit.sortnum
     *
     * @mbggenerated
     */
    public void setSortnum(Integer sortnum) {
        this.sortnum = sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_unit.type
     *
     * @return the value of basic_unit.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_unit.type
     *
     * @param type the value for basic_unit.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_unit.path
     *
     * @return the value of basic_unit.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_unit.path
     *
     * @param path the value for basic_unit.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_unit.stageids
     *
     * @return the value of basic_unit.stageids
     *
     * @mbggenerated
     */
    public String getStageids() {
        return stageids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_unit.stageids
     *
     * @param stageids the value for basic_unit.stageids
     *
     * @mbggenerated
     */
    public void setStageids(String stageids) {
        this.stageids = stageids == null ? null : stageids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_unit.fpinyin
     *
     * @return the value of basic_unit.fpinyin
     *
     * @mbggenerated
     */
    public String getFpinyin() {
        return fpinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_unit.fpinyin
     *
     * @param fpinyin the value for basic_unit.fpinyin
     *
     * @mbggenerated
     */
    public void setFpinyin(String fpinyin) {
        this.fpinyin = fpinyin == null ? null : fpinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_unit.spinyin
     *
     * @return the value of basic_unit.spinyin
     *
     * @mbggenerated
     */
    public String getSpinyin() {
        return spinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_unit.spinyin
     *
     * @param spinyin the value for basic_unit.spinyin
     *
     * @mbggenerated
     */
    public void setSpinyin(String spinyin) {
        this.spinyin = spinyin == null ? null : spinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_unit.createtime
     *
     * @return the value of basic_unit.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_unit.createtime
     *
     * @param createtime the value for basic_unit.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_unit
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Unit other = (Unit) that;
        return (this.getPkid() == null ? other.getPkid() == null : this.getPkid().equals(other.getPkid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getParentid() == null ? other.getParentid() == null : this.getParentid().equals(other.getParentid()))
            && (this.getSortnum() == null ? other.getSortnum() == null : this.getSortnum().equals(other.getSortnum()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getPath() == null ? other.getPath() == null : this.getPath().equals(other.getPath()))
            && (this.getStageids() == null ? other.getStageids() == null : this.getStageids().equals(other.getStageids()))
            && (this.getFpinyin() == null ? other.getFpinyin() == null : this.getFpinyin().equals(other.getFpinyin()))
            && (this.getSpinyin() == null ? other.getSpinyin() == null : this.getSpinyin().equals(other.getSpinyin()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_unit
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPkid() == null) ? 0 : getPkid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getParentid() == null) ? 0 : getParentid().hashCode());
        result = prime * result + ((getSortnum() == null) ? 0 : getSortnum().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getPath() == null) ? 0 : getPath().hashCode());
        result = prime * result + ((getStageids() == null) ? 0 : getStageids().hashCode());
        result = prime * result + ((getFpinyin() == null) ? 0 : getFpinyin().hashCode());
        result = prime * result + ((getSpinyin() == null) ? 0 : getSpinyin().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_unit
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pkid=").append(pkid);
        sb.append(", name=").append(name);
        sb.append(", parentid=").append(parentid);
        sb.append(", sortnum=").append(sortnum);
        sb.append(", type=").append(type);
        sb.append(", path=").append(path);
        sb.append(", stageids=").append(stageids);
        sb.append(", fpinyin=").append(fpinyin);
        sb.append(", spinyin=").append(spinyin);
        sb.append(", createtime=").append(createtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    private int level;
    private Boolean isLast;
    private String unitTypeStr;
    private String stageIdsStr;
    private String manageUserName;

    public String getManageUserName() {
        return manageUserName;
    }

    public void setManageUserName(String manageUserName) {
        this.manageUserName = manageUserName;
    }

    public String getUnitTypeStr() {
        return unitTypeStr;
    }

    public void setUnitTypeStr(String unitTypeStr) {
        this.unitTypeStr = unitTypeStr;
    }

    public String getStageIdsStr() {
        return stageIdsStr;
    }

    public void setStageIdsStr(String stageIdsStr) {
        this.stageIdsStr = stageIdsStr;
    }

    public int getLevel() {
        return level;
    }

    public void setLevel(int level) {
        this.level = level;
    }

    public Boolean getLast() {
        return isLast;
    }

    public void setLast(Boolean last) {
        isLast = last;
    }


}