package com.easybasic.eclassbrand.model;

import java.io.Serializable;

public class ClassRecommend implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecb_classrecommend.pkid
     *
     * @mbggenerated
     */
    private Integer pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecb_classrecommend.classid
     *
     * @mbggenerated
     */
    private Integer classid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecb_classrecommend.recommendid
     *
     * @mbggenerated
     */
    private Integer recommendid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ecb_classrecommend
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecb_classrecommend.pkid
     *
     * @return the value of ecb_classrecommend.pkid
     *
     * @mbggenerated
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecb_classrecommend.pkid
     *
     * @param pkid the value for ecb_classrecommend.pkid
     *
     * @mbggenerated
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecb_classrecommend.classid
     *
     * @return the value of ecb_classrecommend.classid
     *
     * @mbggenerated
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecb_classrecommend.classid
     *
     * @param classid the value for ecb_classrecommend.classid
     *
     * @mbggenerated
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecb_classrecommend.recommendid
     *
     * @return the value of ecb_classrecommend.recommendid
     *
     * @mbggenerated
     */
    public Integer getRecommendid() {
        return recommendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecb_classrecommend.recommendid
     *
     * @param recommendid the value for ecb_classrecommend.recommendid
     *
     * @mbggenerated
     */
    public void setRecommendid(Integer recommendid) {
        this.recommendid = recommendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_classrecommend
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ClassRecommend other = (ClassRecommend) that;
        return (this.getPkid() == null ? other.getPkid() == null : this.getPkid().equals(other.getPkid()))
            && (this.getClassid() == null ? other.getClassid() == null : this.getClassid().equals(other.getClassid()))
            && (this.getRecommendid() == null ? other.getRecommendid() == null : this.getRecommendid().equals(other.getRecommendid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_classrecommend
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPkid() == null) ? 0 : getPkid().hashCode());
        result = prime * result + ((getClassid() == null) ? 0 : getClassid().hashCode());
        result = prime * result + ((getRecommendid() == null) ? 0 : getRecommendid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_classrecommend
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pkid=").append(pkid);
        sb.append(", classid=").append(classid);
        sb.append(", recommendid=").append(recommendid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}