package com.easybasic.kaoqin.dao;

import com.easybasic.kaoqin.model.Appointment;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IAppointmentDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_appointment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_appointment
     *
     * @mbggenerated
     */
    int insert(Appointment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_appointment
     *
     * @mbggenerated
     */
    Appointment selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_appointment
     *
     * @mbggenerated
     */
    List<Appointment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_appointment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Appointment record);
    List<Appointment> selectListBySearch(@Param("searchStr")String searchStr, @Param("orderStr")String orderStr);
}