package com.easybasic.kaoqin.dao;

import com.easybasic.kaoqin.model.OperatLog;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IOperatLogDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_operatlog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_operatlog
     *
     * @mbggenerated
     */
    int insert(OperatLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_operatlog
     *
     * @mbggenerated
     */
    OperatLog selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_operatlog
     *
     * @mbggenerated
     */
    List<OperatLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_operatlog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OperatLog record);
    List<OperatLog> selectListBySearch(@Param("searchStr")String searchStr, @Param("orderStr")String orderStr);
}