package com.easybasic.kaoqin.dao;

import com.easybasic.kaoqin.model.UserGroup;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IUserGroupDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_usergroupanduser
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_usergroupanduser
     *
     * @mbggenerated
     */
    int insert(UserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_usergroupanduser
     *
     * @mbggenerated
     */
    UserGroup selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_usergroupanduser
     *
     * @mbggenerated
     */
    List<UserGroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_usergroupanduser
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserGroup record);
    List<UserGroup> selectListBySearch(@Param("searchStr")String searchStr, @Param("orderStr")String orderStr);
}