package com.easybasic.kaoqin.dao;

import com.easybasic.kaoqin.model.UserCheckInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IUserCheckInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_usercheckinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_usercheckinfo
     *
     * @mbggenerated
     */
    int insert(UserCheckInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_usercheckinfo
     *
     * @mbggenerated
     */
    UserCheckInfo selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_usercheckinfo
     *
     * @mbggenerated
     */
    List<UserCheckInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_usercheckinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserCheckInfo record);
    List<UserCheckInfo> selectListBySearch(@Param("searchStr")String searchStr, @Param("orderStr")String orderStr);
}