package com.easybasic.edu.dao;

import com.easybasic.edu.model.SchoolGradeSubject;
import java.util.List;

public interface ISchoolGradeSubjectDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_schoolgradesubject
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_schoolgradesubject
     *
     * @mbggenerated
     */
    int insert(SchoolGradeSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_schoolgradesubject
     *
     * @mbggenerated
     */
    SchoolGradeSubject selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_schoolgradesubject
     *
     * @mbggenerated
     */
    List<SchoolGradeSubject> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_schoolgradesubject
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SchoolGradeSubject record);
}