package com.easybasic.edu.dao;

import com.easybasic.edu.model.SchoolClassCurriculum;
import java.util.List;

public interface ISchoolClassCurriculumDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_schoolclasscurriculum
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_schoolclasscurriculum
     *
     * @mbggenerated
     */
    int insert(SchoolClassCurriculum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_schoolclasscurriculum
     *
     * @mbggenerated
     */
    SchoolClassCurriculum selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_schoolclasscurriculum
     *
     * @mbggenerated
     */
    List<SchoolClassCurriculum> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_schoolclasscurriculum
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SchoolClassCurriculum record);
    List<SchoolClassCurriculum> selectListBySchoolIdAndClassId(int schoolId, int classId);
    SchoolClassCurriculum selectBySchoolIdAndClassIdAndWeekAndSession(int schoolId, int classId, int week,int session);
}