package com.easybasic.edu.model;

import java.io.Serializable;

public class SchoolClassCurriculum implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_schoolclasscurriculum.pkid
     *
     * @mbggenerated
     */
    private Integer pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_schoolclasscurriculum.schoolid
     *
     * @mbggenerated
     */
    private Integer schoolid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_schoolclasscurriculum.classid
     *
     * @mbggenerated
     */
    private Integer classid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_schoolclasscurriculum.week
     *
     * @mbggenerated
     */
    private Integer week;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_schoolclasscurriculum.session
     *
     * @mbggenerated
     */
    private Integer session;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_schoolclasscurriculum.teacherid
     *
     * @mbggenerated
     */
    private Integer teacherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_schoolclasscurriculum.subjectid
     *
     * @mbggenerated
     */
    private Integer subjectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table edu_schoolclasscurriculum
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_schoolclasscurriculum.pkid
     *
     * @return the value of edu_schoolclasscurriculum.pkid
     *
     * @mbggenerated
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_schoolclasscurriculum.pkid
     *
     * @param pkid the value for edu_schoolclasscurriculum.pkid
     *
     * @mbggenerated
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_schoolclasscurriculum.schoolid
     *
     * @return the value of edu_schoolclasscurriculum.schoolid
     *
     * @mbggenerated
     */
    public Integer getSchoolid() {
        return schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_schoolclasscurriculum.schoolid
     *
     * @param schoolid the value for edu_schoolclasscurriculum.schoolid
     *
     * @mbggenerated
     */
    public void setSchoolid(Integer schoolid) {
        this.schoolid = schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_schoolclasscurriculum.classid
     *
     * @return the value of edu_schoolclasscurriculum.classid
     *
     * @mbggenerated
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_schoolclasscurriculum.classid
     *
     * @param classid the value for edu_schoolclasscurriculum.classid
     *
     * @mbggenerated
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_schoolclasscurriculum.week
     *
     * @return the value of edu_schoolclasscurriculum.week
     *
     * @mbggenerated
     */
    public Integer getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_schoolclasscurriculum.week
     *
     * @param week the value for edu_schoolclasscurriculum.week
     *
     * @mbggenerated
     */
    public void setWeek(Integer week) {
        this.week = week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_schoolclasscurriculum.session
     *
     * @return the value of edu_schoolclasscurriculum.session
     *
     * @mbggenerated
     */
    public Integer getSession() {
        return session;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_schoolclasscurriculum.session
     *
     * @param session the value for edu_schoolclasscurriculum.session
     *
     * @mbggenerated
     */
    public void setSession(Integer session) {
        this.session = session;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_schoolclasscurriculum.teacherid
     *
     * @return the value of edu_schoolclasscurriculum.teacherid
     *
     * @mbggenerated
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_schoolclasscurriculum.teacherid
     *
     * @param teacherid the value for edu_schoolclasscurriculum.teacherid
     *
     * @mbggenerated
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_schoolclasscurriculum.subjectid
     *
     * @return the value of edu_schoolclasscurriculum.subjectid
     *
     * @mbggenerated
     */
    public Integer getSubjectid() {
        return subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_schoolclasscurriculum.subjectid
     *
     * @param subjectid the value for edu_schoolclasscurriculum.subjectid
     *
     * @mbggenerated
     */
    public void setSubjectid(Integer subjectid) {
        this.subjectid = subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_schoolclasscurriculum
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SchoolClassCurriculum other = (SchoolClassCurriculum) that;
        return (this.getPkid() == null ? other.getPkid() == null : this.getPkid().equals(other.getPkid()))
            && (this.getSchoolid() == null ? other.getSchoolid() == null : this.getSchoolid().equals(other.getSchoolid()))
            && (this.getClassid() == null ? other.getClassid() == null : this.getClassid().equals(other.getClassid()))
            && (this.getWeek() == null ? other.getWeek() == null : this.getWeek().equals(other.getWeek()))
            && (this.getSession() == null ? other.getSession() == null : this.getSession().equals(other.getSession()))
            && (this.getTeacherid() == null ? other.getTeacherid() == null : this.getTeacherid().equals(other.getTeacherid()))
            && (this.getSubjectid() == null ? other.getSubjectid() == null : this.getSubjectid().equals(other.getSubjectid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_schoolclasscurriculum
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPkid() == null) ? 0 : getPkid().hashCode());
        result = prime * result + ((getSchoolid() == null) ? 0 : getSchoolid().hashCode());
        result = prime * result + ((getClassid() == null) ? 0 : getClassid().hashCode());
        result = prime * result + ((getWeek() == null) ? 0 : getWeek().hashCode());
        result = prime * result + ((getSession() == null) ? 0 : getSession().hashCode());
        result = prime * result + ((getTeacherid() == null) ? 0 : getTeacherid().hashCode());
        result = prime * result + ((getSubjectid() == null) ? 0 : getSubjectid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_schoolclasscurriculum
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pkid=").append(pkid);
        sb.append(", schoolid=").append(schoolid);
        sb.append(", classid=").append(classid);
        sb.append(", week=").append(week);
        sb.append(", session=").append(session);
        sb.append(", teacherid=").append(teacherid);
        sb.append(", subjectid=").append(subjectid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    private String teacherName;
    private String subjectName;

    public String getTeacherName() {
        return teacherName;
    }

    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }

    public String getSubjectName() {
        return subjectName;
    }

    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }
}
