package com.easybasic.edu.model;

import java.io.Serializable;

public class SchoolGradeSubject implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_schoolgradesubject.pkid
     *
     * @mbggenerated
     */
    private Integer pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_schoolgradesubject.schoolid
     *
     * @mbggenerated
     */
    private Integer schoolid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_schoolgradesubject.stageid
     *
     * @mbggenerated
     */
    private Integer stageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_schoolgradesubject.gradeid
     *
     * @mbggenerated
     */
    private Integer gradeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_schoolgradesubject.subjectid
     *
     * @mbggenerated
     */
    private Integer subjectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table edu_schoolgradesubject
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_schoolgradesubject.pkid
     *
     * @return the value of edu_schoolgradesubject.pkid
     *
     * @mbggenerated
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_schoolgradesubject.pkid
     *
     * @param pkid the value for edu_schoolgradesubject.pkid
     *
     * @mbggenerated
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_schoolgradesubject.schoolid
     *
     * @return the value of edu_schoolgradesubject.schoolid
     *
     * @mbggenerated
     */
    public Integer getSchoolid() {
        return schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_schoolgradesubject.schoolid
     *
     * @param schoolid the value for edu_schoolgradesubject.schoolid
     *
     * @mbggenerated
     */
    public void setSchoolid(Integer schoolid) {
        this.schoolid = schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_schoolgradesubject.stageid
     *
     * @return the value of edu_schoolgradesubject.stageid
     *
     * @mbggenerated
     */
    public Integer getStageid() {
        return stageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_schoolgradesubject.stageid
     *
     * @param stageid the value for edu_schoolgradesubject.stageid
     *
     * @mbggenerated
     */
    public void setStageid(Integer stageid) {
        this.stageid = stageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_schoolgradesubject.gradeid
     *
     * @return the value of edu_schoolgradesubject.gradeid
     *
     * @mbggenerated
     */
    public Integer getGradeid() {
        return gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_schoolgradesubject.gradeid
     *
     * @param gradeid the value for edu_schoolgradesubject.gradeid
     *
     * @mbggenerated
     */
    public void setGradeid(Integer gradeid) {
        this.gradeid = gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_schoolgradesubject.subjectid
     *
     * @return the value of edu_schoolgradesubject.subjectid
     *
     * @mbggenerated
     */
    public Integer getSubjectid() {
        return subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_schoolgradesubject.subjectid
     *
     * @param subjectid the value for edu_schoolgradesubject.subjectid
     *
     * @mbggenerated
     */
    public void setSubjectid(Integer subjectid) {
        this.subjectid = subjectid;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_schoolgradesubject
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SchoolGradeSubject other = (SchoolGradeSubject) that;
        return (this.getPkid() == null ? other.getPkid() == null : this.getPkid().equals(other.getPkid()))
            && (this.getSchoolid() == null ? other.getSchoolid() == null : this.getSchoolid().equals(other.getSchoolid()))
            && (this.getStageid() == null ? other.getStageid() == null : this.getStageid().equals(other.getStageid()))
            && (this.getGradeid() == null ? other.getGradeid() == null : this.getGradeid().equals(other.getGradeid()))
            && (this.getSubjectid() == null ? other.getSubjectid() == null : this.getSubjectid().equals(other.getSubjectid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_schoolgradesubject
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPkid() == null) ? 0 : getPkid().hashCode());
        result = prime * result + ((getSchoolid() == null) ? 0 : getSchoolid().hashCode());
        result = prime * result + ((getStageid() == null) ? 0 : getStageid().hashCode());
        result = prime * result + ((getGradeid() == null) ? 0 : getGradeid().hashCode());
        result = prime * result + ((getSubjectid() == null) ? 0 : getSubjectid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_schoolgradesubject
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pkid=").append(pkid);
        sb.append(", schoolid=").append(schoolid);
        sb.append(", stageid=").append(stageid);
        sb.append(", gradeid=").append(gradeid);
        sb.append(", subjectid=").append(subjectid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}