package com.easybasic.kaoqin.model;

import java.io.Serializable;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;
public class PlanWeek implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_planweek.pkid
     *
     * @mbggenerated
     */
    private Integer pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_planweek.UserGroupIDStr
     *
     * @mbggenerated
     */
    private String usergroupidstr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_planweek.Subject
     *
     * @mbggenerated
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_planweek.BeginTime
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date begintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_planweek.EndTime
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_planweek.WeekNo
     *
     * @mbggenerated
     */
    private String weekno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_planweek.WeekOrder
     *
     * @mbggenerated
     */
    private Integer weekorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_planweek.SchoolID
     *
     * @mbggenerated
     */
    private Integer schoolid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_planweek.SpaceID
     *
     * @mbggenerated
     */
    private Integer spaceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_planweek.teacherID
     *
     * @mbggenerated
     */
    private Integer teacherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kq_planweek
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_planweek.pkid
     *
     * @return the value of kq_planweek.pkid
     *
     * @mbggenerated
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_planweek.pkid
     *
     * @param pkid the value for kq_planweek.pkid
     *
     * @mbggenerated
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_planweek.UserGroupIDStr
     *
     * @return the value of kq_planweek.UserGroupIDStr
     *
     * @mbggenerated
     */
    public String getUsergroupidstr() {
        return usergroupidstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_planweek.UserGroupIDStr
     *
     * @param usergroupidstr the value for kq_planweek.UserGroupIDStr
     *
     * @mbggenerated
     */
    public void setUsergroupidstr(String usergroupidstr) {
        this.usergroupidstr = usergroupidstr == null ? null : usergroupidstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_planweek.Subject
     *
     * @return the value of kq_planweek.Subject
     *
     * @mbggenerated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_planweek.Subject
     *
     * @param subject the value for kq_planweek.Subject
     *
     * @mbggenerated
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_planweek.BeginTime
     *
     * @return the value of kq_planweek.BeginTime
     *
     * @mbggenerated
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_planweek.BeginTime
     *
     * @param begintime the value for kq_planweek.BeginTime
     *
     * @mbggenerated
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_planweek.EndTime
     *
     * @return the value of kq_planweek.EndTime
     *
     * @mbggenerated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_planweek.EndTime
     *
     * @param endtime the value for kq_planweek.EndTime
     *
     * @mbggenerated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_planweek.WeekNo
     *
     * @return the value of kq_planweek.WeekNo
     *
     * @mbggenerated
     */
    public String getWeekno() {
        return weekno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_planweek.WeekNo
     *
     * @param weekno the value for kq_planweek.WeekNo
     *
     * @mbggenerated
     */
    public void setWeekno(String weekno) {
        this.weekno = weekno == null ? null : weekno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_planweek.WeekOrder
     *
     * @return the value of kq_planweek.WeekOrder
     *
     * @mbggenerated
     */
    public Integer getWeekorder() {
        return weekorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_planweek.WeekOrder
     *
     * @param weekorder the value for kq_planweek.WeekOrder
     *
     * @mbggenerated
     */
    public void setWeekorder(Integer weekorder) {
        this.weekorder = weekorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_planweek.SchoolID
     *
     * @return the value of kq_planweek.SchoolID
     *
     * @mbggenerated
     */
    public Integer getSchoolid() {
        return schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_planweek.SchoolID
     *
     * @param schoolid the value for kq_planweek.SchoolID
     *
     * @mbggenerated
     */
    public void setSchoolid(Integer schoolid) {
        this.schoolid = schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_planweek.SpaceID
     *
     * @return the value of kq_planweek.SpaceID
     *
     * @mbggenerated
     */
    public Integer getSpaceid() {
        return spaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_planweek.SpaceID
     *
     * @param spaceid the value for kq_planweek.SpaceID
     *
     * @mbggenerated
     */
    public void setSpaceid(Integer spaceid) {
        this.spaceid = spaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_planweek.teacherID
     *
     * @return the value of kq_planweek.teacherID
     *
     * @mbggenerated
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_planweek.teacherID
     *
     * @param teacherid the value for kq_planweek.teacherID
     *
     * @mbggenerated
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_planweek
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PlanWeek other = (PlanWeek) that;
        return (this.getPkid() == null ? other.getPkid() == null : this.getPkid().equals(other.getPkid()))
            && (this.getUsergroupidstr() == null ? other.getUsergroupidstr() == null : this.getUsergroupidstr().equals(other.getUsergroupidstr()))
            && (this.getSubject() == null ? other.getSubject() == null : this.getSubject().equals(other.getSubject()))
            && (this.getBegintime() == null ? other.getBegintime() == null : this.getBegintime().equals(other.getBegintime()))
            && (this.getEndtime() == null ? other.getEndtime() == null : this.getEndtime().equals(other.getEndtime()))
            && (this.getWeekno() == null ? other.getWeekno() == null : this.getWeekno().equals(other.getWeekno()))
            && (this.getWeekorder() == null ? other.getWeekorder() == null : this.getWeekorder().equals(other.getWeekorder()))
            && (this.getSchoolid() == null ? other.getSchoolid() == null : this.getSchoolid().equals(other.getSchoolid()))
            && (this.getSpaceid() == null ? other.getSpaceid() == null : this.getSpaceid().equals(other.getSpaceid()))
            && (this.getTeacherid() == null ? other.getTeacherid() == null : this.getTeacherid().equals(other.getTeacherid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_planweek
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPkid() == null) ? 0 : getPkid().hashCode());
        result = prime * result + ((getUsergroupidstr() == null) ? 0 : getUsergroupidstr().hashCode());
        result = prime * result + ((getSubject() == null) ? 0 : getSubject().hashCode());
        result = prime * result + ((getBegintime() == null) ? 0 : getBegintime().hashCode());
        result = prime * result + ((getEndtime() == null) ? 0 : getEndtime().hashCode());
        result = prime * result + ((getWeekno() == null) ? 0 : getWeekno().hashCode());
        result = prime * result + ((getWeekorder() == null) ? 0 : getWeekorder().hashCode());
        result = prime * result + ((getSchoolid() == null) ? 0 : getSchoolid().hashCode());
        result = prime * result + ((getSpaceid() == null) ? 0 : getSpaceid().hashCode());
        result = prime * result + ((getTeacherid() == null) ? 0 : getTeacherid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_planweek
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pkid=").append(pkid);
        sb.append(", usergroupidstr=").append(usergroupidstr);
        sb.append(", subject=").append(subject);
        sb.append(", begintime=").append(begintime);
        sb.append(", endtime=").append(endtime);
        sb.append(", weekno=").append(weekno);
        sb.append(", weekorder=").append(weekorder);
        sb.append(", schoolid=").append(schoolid);
        sb.append(", spaceid=").append(spaceid);
        sb.append(", teacherid=").append(teacherid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}