package com.easybasic.resourceget.model;

import java.io.Serializable;
import java.util.Date;

public class Terminal implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_ds.pkid
     *
     * @mbggenerated
     */
    private Integer pkid;
    private String name;
    private Integer categoryid;
    private String terminalos;
    private String terminalip;
    private String online;
    private String code;
    private String version;
    private String spacename;
    private Integer mode;
    private Integer ispatrol;
    private Integer isattendance;
    private static final long serialVersionUID = 1L;

    public Integer getPkid() {
        return pkid;
    }
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public Integer getCategoryid(){return categoryid;}
    public void setCategoryid(Integer categoryid){this.categoryid=categoryid;}

    public String getTerminalos() {
        return terminalos;
    }
    public void setTerminalos(String terminalos) {
        this.terminalos = terminalos == null ? null : terminalos.trim();
    }

    public String getTerminalip() {
        return terminalip;
    }
    public void setTerminalip(String terminalip) {
        this.terminalip = terminalip == null ? null : terminalip.trim();
    }

    public String getOnline() {
        return online;
    }
    public void setOnline(String online) {
        this.online = online == null ? null : online.trim();
    }

    public String getCode() {
        return code;
    }
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    public String getVersion() {
        return version;
    }
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    public String getSpacename() { return spacename; }
    public void setSpacename(String spacename) { this.spacename = spacename == null ? null : spacename.trim(); }

    public Integer getMode() {
        return mode;
    }
    public void setMode(Integer mode) {
        this.mode = mode;
    }

    public Integer getIspatrol() {
        return ispatrol;
    }
    public void setIspatrol(Integer ispatrol) {
        this.ispatrol = ispatrol;
    }

    public Integer getIsattendance() {
        return isattendance;
    }
    public void setIsattendance(Integer isattendance) {
        this.isattendance = isattendance;
    }
}