package com.easybasic.basic.dao;

import com.easybasic.basic.model.AppMenu;
import java.util.List;

public interface IAppMenuDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_appmenu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_appmenu
     *
     * @mbggenerated
     */
    int insert(AppMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_appmenu
     *
     * @mbggenerated
     */
    AppMenu selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_appmenu
     *
     * @mbggenerated
     */
    List<AppMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_appmenu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppMenu record);

    List<AppMenu> selectListByAppId(int appId);
    List<AppMenu> selectListByParentId(int parentId);
    List<AppMenu> selectListByAppIdForMenu(int appId);
}