package com.easybasic.basic.dao;

import com.easybasic.basic.model.DataDicValDetail;
import java.util.List;

public interface IDataDicValDetailDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_datadicvaldetail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_datadicvaldetail
     *
     * @mbggenerated
     */
    int insert(DataDicValDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_datadicvaldetail
     *
     * @mbggenerated
     */
    DataDicValDetail selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_datadicvaldetail
     *
     * @mbggenerated
     */
    List<DataDicValDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_datadicvaldetail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DataDicValDetail record);

    List<DataDicValDetail> selectListByDCode(String dcode);
}