package com.easybasic.basic.dao;

import com.easybasic.basic.model.Dept;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IDeptDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_dept
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_dept
     *
     * @mbggenerated
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_dept
     *
     * @mbggenerated
     */
    Dept selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_dept
     *
     * @mbggenerated
     */
    List<Dept> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_dept
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Dept record);

    List<Dept> selectListBySearch(@Param("searchStr")String searchStr, @Param("orderStr")String orderStr);
}