package com.easybasic.basic.dao;

import com.easybasic.basic.model.IntranetIp;
import java.util.List;

public interface IIntranetIpDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_intranetip
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_intranetip
     *
     * @mbggenerated
     */
    int insert(IntranetIp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_intranetip
     *
     * @mbggenerated
     */
    IntranetIp selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_intranetip
     *
     * @mbggenerated
     */
    List<IntranetIp> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_intranetip
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IntranetIp record);
}