package com.easybasic.basic.dao;

import com.easybasic.basic.model.OnlineUser;
import java.util.List;

public interface IOnlineUserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_onlineuser
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_onlineuser
     *
     * @mbggenerated
     */
    int insert(OnlineUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_onlineuser
     *
     * @mbggenerated
     */
    OnlineUser selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_onlineuser
     *
     * @mbggenerated
     */
    List<OnlineUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_onlineuser
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OnlineUser record);
    OnlineUser selectByUserId(int userId);
    int deleteByValidate();
    OnlineUser selectByCode(String code);
}