package com.easybasic.basic.dao;

import com.easybasic.basic.model.OpLog;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IOpLogDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_oplog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_oplog
     *
     * @mbggenerated
     */
    int insert(OpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_oplog
     *
     * @mbggenerated
     */
    OpLog selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_oplog
     *
     * @mbggenerated
     */
    List<OpLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_oplog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OpLog record);
    List<OpLog> selectListBySearch(@Param("searchStr")String searchStr, @Param("orderStr")String orderStr);
    int deleteByUnValidate();
}