package com.easybasic.basic.dao;

import com.easybasic.basic.model.PurviewRole;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IPurviewRoleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_purviewrole
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_purviewrole
     *
     * @mbggenerated
     */
    int insert(PurviewRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_purviewrole
     *
     * @mbggenerated
     */
    PurviewRole selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_purviewrole
     *
     * @mbggenerated
     */
    List<PurviewRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_purviewrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PurviewRole record);
    List<PurviewRole> selectListBySearch(@Param("searchStr")String searchStr, @Param("orderStr")String orderStr);
}