package com.easybasic.basic.dao;

import com.easybasic.basic.model.PurviewRoleUser;
import java.util.List;

public interface IPurviewRoleUserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_purviewroleuser
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_purviewroleuser
     *
     * @mbggenerated
     */
    int insert(PurviewRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_purviewroleuser
     *
     * @mbggenerated
     */
    PurviewRoleUser selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_purviewroleuser
     *
     * @mbggenerated
     */
    List<PurviewRoleUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_purviewroleuser
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PurviewRoleUser record);

    PurviewRoleUser selectByRoleIdAndUserId(int roleId, int userId);
    List<PurviewRoleUser> selectListByUserId(int userId);
    List<PurviewRoleUser> selectListByRoleId(int roleId);
}