package com.easybasic.basic.dao;

import com.easybasic.basic.model.SchoolClassUser;
import java.util.List;

public interface ISchoolClassUserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_schoolclassuser
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_schoolclassuser
     *
     * @mbggenerated
     */
    int insert(SchoolClassUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_schoolclassuser
     *
     * @mbggenerated
     */
    SchoolClassUser selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_schoolclassuser
     *
     * @mbggenerated
     */
    List<SchoolClassUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_schoolclassuser
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SchoolClassUser record);
    int selectCountByClassId(int classId);
    SchoolClassUser selectStudentByUserId(int userId);
    List<SchoolClassUser> selectTeacherListByUserId(int userId);
}