package com.easybasic.basic.dao;

import com.easybasic.basic.model.SchoolClassTeacher;
import java.util.List;

public interface ISchoolClassTeacherDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_schoolclassteacher
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_schoolclassteacher
     *
     * @mbggenerated
     */
    int insert(SchoolClassTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_schoolclassteacher
     *
     * @mbggenerated
     */
    SchoolClassTeacher selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_schoolclassteacher
     *
     * @mbggenerated
     */
    List<SchoolClassTeacher> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_schoolclassteacher
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SchoolClassTeacher record);
    List<SchoolClassTeacher> selectTeacherByClassId(int classId);
    SchoolClassTeacher selectStudentByUserId(int userId);
    List<SchoolClassTeacher> selectTeacherListByUserId(int userId);
}