package com.easybasic.basic.dao;

import com.easybasic.basic.model.SiteConfig;
import java.util.List;

public interface ISiteConfigDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_siteconfig
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_siteconfig
     *
     * @mbggenerated
     */
    int insert(SiteConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_siteconfig
     *
     * @mbggenerated
     */
    SiteConfig selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_siteconfig
     *
     * @mbggenerated
     */
    List<SiteConfig> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_siteconfig
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SiteConfig record);
}