package com.easybasic.basic.dao;

import com.easybasic.basic.model.SpaceType;
import java.util.List;

public interface ISpaceTypeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_spacetype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_spacetype
     *
     * @mbggenerated
     */
    int insert(SpaceType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_spacetype
     *
     * @mbggenerated
     */
    SpaceType selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_spacetype
     *
     * @mbggenerated
     */
    List<SpaceType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_spacetype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SpaceType record);

    List<SpaceType> selectListByUnitId(int unitId);
}