package com.easybasic.basic.dao;

import com.easybasic.basic.model.Space;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ISpaceDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_space
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_space
     *
     * @mbggenerated
     */
    int insert(Space record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_space
     *
     * @mbggenerated
     */
    Space selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_space
     *
     * @mbggenerated
     */
    List<Space> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_space
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Space record);

    List<Space> selectListBySearch(@Param("searchStr")String searchStr, @Param("orderStr")String orderStr);
    Space selectByClassId(int classId);
}
