package com.easybasic.basic.dao;

import com.easybasic.basic.model.Student;
import java.util.List;

public interface IStudentDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_student
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_student
     *
     * @mbggenerated
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_student
     *
     * @mbggenerated
     */
    Student selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_student
     *
     * @mbggenerated
     */
    List<Student> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_student
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Student record);
    Student selectByUserId(int userId);
}