package com.easybasic.basic.dao;

import com.easybasic.basic.model.Teacher;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ITeacherDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_teacher
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_teacher
     *
     * @mbggenerated
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_teacher
     *
     * @mbggenerated
     */
    Teacher selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_teacher
     *
     * @mbggenerated
     */
    List<Teacher> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_teacher
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Teacher record);
    Teacher selectByUserId(int userId);
    List<Teacher> selectListBySearch(@Param("searchStr")String searchStr);
}