package com.easybasic.eclassbrand.dao;

import com.easybasic.eclassbrand.model.Activity;
import com.easybasic.eclassbrand.model.ActivityDetail;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IActivityDetailDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_activitydetail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_activitydetail
     *
     * @mbggenerated
     */
    int insert(ActivityDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_activitydetail
     *
     * @mbggenerated
     */
    ActivityDetail selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_activitydetail
     *
     * @mbggenerated
     */
    List<ActivityDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_activitydetail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ActivityDetail record);
    List<ActivityDetail> selectListBySearch(@Param("searchStr") String searchStr, @Param("orderStr") String orderStr);
}