package com.easybasic.eclassbrand.dao;

import com.easybasic.eclassbrand.model.Activity;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IActivityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_activity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_activity
     *
     * @mbggenerated
     */
    int insert(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_activity
     *
     * @mbggenerated
     */
    Activity selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_activity
     *
     * @mbggenerated
     */
    List<Activity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Activity record);
    List<Activity> selectListBySearch(@Param("searchStr") String searchStr, @Param("orderStr") String orderStr);
}