package com.easybasic.eclassbrand.dao;

import com.easybasic.eclassbrand.model.ClassActivity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IClassActivityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_classactivity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_classactivity
     *
     * @mbggenerated
     */
    int insert(ClassActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_classactivity
     *
     * @mbggenerated
     */
    ClassActivity selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_classactivity
     *
     * @mbggenerated
     */
    List<ClassActivity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_classactivity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ClassActivity record);
    List<ClassActivity> selectListBySearch(@Param("searchStr")String searchStr, @Param("orderStr")String orderStr);
    ClassActivity getByClassIdAndTaskId(int classid,int taskid);
}