package com.easybasic.eclassbrand.dao;

import com.easybasic.eclassbrand.model.CleanHealth;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ICleanHealthDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_cleanhealth
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_cleanhealth
     *
     * @mbggenerated
     */
    int insert(CleanHealth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_cleanhealth
     *
     * @mbggenerated
     */
    CleanHealth selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_cleanhealth
     *
     * @mbggenerated
     */
    List<CleanHealth> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_cleanhealth
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CleanHealth record);
    List<CleanHealth> selectListBySearch(@Param("searchStr")String searchStr, @Param("orderStr")String orderStr);
}