package com.easybasic.eclassbrand.dao;

import com.easybasic.eclassbrand.model.ClassTask;
import com.easybasic.eclassbrand.model.ExamRoom;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IExamRoomDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_examroom
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_examroom
     *
     * @mbggenerated
     */
    int insert(ExamRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_examroom
     *
     * @mbggenerated
     */
    ExamRoom selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_examroom
     *
     * @mbggenerated
     */
    List<ExamRoom> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_examroom
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExamRoom record);
    List<ExamRoom> selectListBySearch(@Param("searchStr")String searchStr, @Param("orderStr")String orderStr);
    ExamRoom getBySpaceId(int spaceid);
}