package com.easybasic.eclassbrand.dao;

import com.easybasic.eclassbrand.model.HonorCategory;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IHonorCategoryDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_honorcategory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_honorcategory
     *
     * @mbggenerated
     */
    int insert(HonorCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_honorcategory
     *
     * @mbggenerated
     */
    HonorCategory selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_honorcategory
     *
     * @mbggenerated
     */
    List<HonorCategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_honorcategory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HonorCategory record);
    List<HonorCategory> selectListBySearch(@Param("searchStr")String searchStr, @Param("orderStr")String orderStr);
}