package com.easybasic.eclassbrand.dao;

import com.easybasic.eclassbrand.model.News;
import org.apache.ibatis.annotations.Param;
import java.util.List;

public interface INewsDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_news
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_news
     *
     * @mbggenerated
     */
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_news
     *
     * @mbggenerated
     */
    News selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_news
     *
     * @mbggenerated
     */
    List<News> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(News record);
    List<News> selectListBySearch(@Param("searchStr") String searchStr, @Param("orderStr") String orderStr);
}