package com.easybasic.eclassbrand.dao;

import com.easybasic.eclassbrand.model.NewsType;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface INewsTypeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_newstype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_newstype
     *
     * @mbggenerated
     */
    int insert(NewsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_newstype
     *
     * @mbggenerated
     */
    NewsType selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_newstype
     *
     * @mbggenerated
     */
    List<NewsType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_newstype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NewsType record);
    List<NewsType> selectListBySearch(@Param("searchStr") String searchStr, @Param("orderStr") String orderStr);
}