package com.easybasic.eclassbrand.dao;

import com.easybasic.eclassbrand.model.Task;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ITaskDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_task
     *
     * @mbggenerated
     */
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_task
     *
     * @mbggenerated
     */
    Task selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_task
     *
     * @mbggenerated
     */
    List<Task> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Task record);
    List<Task> selectListBySearch(@Param("searchStr")String searchStr, @Param("orderStr")String orderStr);
}