package com.easybasic.eclassbrand.dao;

import com.easybasic.eclassbrand.model.Website;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IWebsiteDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_website
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_website
     *
     * @mbggenerated
     */
    int insert(Website record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_website
     *
     * @mbggenerated
     */
    Website selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_website
     *
     * @mbggenerated
     */
    List<Website> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecb_website
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Website record);
    List<Website> selectListBySearch(@Param("searchStr")String searchStr, @Param("orderStr")String orderStr);
}